---
- hosts: chocolatey_business_clients
  gather_facts: false

  tasks:
    - name: 'Install outdated version of Firefox'
      win_chocolatey:
        name: 'firefox'
        version: "69.0.1"

    - name: 'Install outdated version of VLC'
      win_chocolatey:
        name: 'vlc'
        version: "2.2.8"

    # we do this so we don't have to wait for the agent to check in on it's normal schedule
    - win_service:
        name: 'chocolatey-agent'
        state: restarted