---
- hosts: chocolatey_business_clients
  gather_facts: false

  tasks:
    - name: 'Update all software '
      win_chocolatey:
        name: all
        state: latest

    # we do this so we don't have to wait for the agent to check in on it's normal schedule
    - name: "Restart Chocolatey agent so we don't have to wait on it checking in for this demo"
      win_service:
        name: 'chocolatey-agent'
        state: restarted