---
- hosts: localhost
  gather_facts: false

  tasks:
    - set_fact:
        instance_name: "win{{ 100 | random }}"
      run_once: true
      when: instance_name is undefined

    - name: 'Create public IP address'
      azure_rm_publicipaddress:
        resource_group: "{{ azure_resource_group }}"
        allocation_method: Static
        domain_name: "{{ instance_name }}"
        name: "{{ instance_name }}-publicip"
      register: output_ip_address

    - name: 'Output public IP address'
      debug:
        msg: "The public IP address of {{ instance_name }} is {{ output_ip_address.state.ip_address }}"

    - name: 'Create network security group'
      azure_rm_securitygroup:
        resource_group: "{{ azure_resource_group }}"
        name: "{{ instance_name }}-nsg"
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range:
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound

    - name: 'Create virtual NIC'
      azure_rm_networkinterface:
        name: "{{ instance_name }}-nic"
        resource_group: "{{ azure_resource_group }}"
        virtual_network: "vnet-{{ azure_resource_group }}"
        subnet_name: "subnet-{{ azure_resource_group }}"
        security_group: "{{ instance_name }}-nsg"
        ip_configurations:
          - name: "{{ instance_name }}-ip"
            public_ip_address_name: "{{ instance_name }}-publicip"
            primary: True

    - name: 'Create VM'
      azure_rm_virtualmachine:
        name: "{{ instance_name }}-vm"
        vm_size: "{{ azure_vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        resource_group: "{{ azure_resource_group }}"
        network_interfaces: "{{ instance_name }}-nic"
        os_type: Windows
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest

    - name: 'Enable HTTPS WinRM listener'
      azure_rm_virtualmachineextension:
        name: winrm-extension
        resource_group: "{{ azure_resource_group }}"
        virtual_machine_name: "{{ instance_name }}-vm"
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: '1.10'
        settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
        auto_upgrade_minor_version: true

    - name: 'Add Ansible user'
      azure_rm_virtualmachineextension:
        name: winrm-extension
        resource_group: "{{ azure_resource_group }}"
        virtual_machine_name: "{{ instance_name }}-vm"
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: '1.10'
        settings: '{"fileUris": ["https://gist.githubusercontent.com/pauby/01d1cc5a8c1fcd82c391618ec41813da/raw/fdff6adfcd836872660a26ccc243b2b2782a3c98/AddUser.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File AddUser.ps1 -Username ""{{ my_ansible_user }}"" -Password ""{{ my_ansible_password }}""" }'
        auto_upgrade_minor_version: true